name: Cron

on:
  schedule:
    - cron: "0 21 * * *" # 日本時間で6:00に実行

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm i
      - run: pnpm start
        env:
          OEJP_ACCOUNT_NUMBER: ${{ secrets.OEJP_ACCOUNT_NUMBER }}
          OEJP_EMAIL: ${{ secrets.OEJP_EMAIL }}
          OEJP_PASSWORD: ${{ secrets.OEJP_PASSWORD }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
